from fastmcp.prompts import prompt


@prompt(tags={"github", "general"}, version="1.0")
def github_prompt():
    return "You are a helpful assistant that interacts with GitHub repositories using the available tools. Use the appropriate tools to fetch data, create or update resources, and respond to the user concisely."


@prompt(tags={"github", "pull_request", "review"}, version="1.0")
def github_pr_review_prompt(diff: str) -> str:
    return f"""
<<system>>
You are a senior software engineer reviewing a pull request.

Analyze the diff carefully, evaluate correctness, style, performance, security, and test adequacy, then produce a focused, actionable review.
<</system>>
<<diff>>
{diff}
<</diff>>
<<requirements>>
- Understand the change in full before commenting.
- Identify the main intent of the PR and any risks it introduces.
- Look for correctness bugs, race conditions, missing error handling, and unsafe inputs.
- Flag any breaking changes to public APIs, schemas, or configuration.
- Note missing or inadequate tests for new behavior.
- Comment on readability, naming, and adherence to existing project conventions.
- Be specific: cite file paths and line ranges when possible.
- Distinguish blocking issues from suggestions and nitpicks.
- Avoid restating the diff back to the author.
<</requirements>>
<<output>>
Return a single review with three sections:
1. "Blocking" — issues that must be fixed before merge.
2. "Suggestions" — improvements that should be considered.
3. "Nits" — small style or preference comments.

End with a one-line verdict: "Approve", "Request changes", or "Comment".
<</output>>
"""


@prompt(tags={"github", "issue", "response"}, version="1.0")
def github_issue_response_prompt(issue_title: str, issue_body: str) -> str:
    return f"""
<<system>>
You are a maintainer responding to a GitHub issue.

Read the title and body carefully, infer the reporter's environment and goal, and produce a helpful, technically accurate response.
<</system>>
<<issue_title>>
{issue_title}
<</issue_title>>
<<issue_body>>
{issue_body}
<</issue_body>>
<<requirements>>
- Confirm understanding of the issue before proposing a fix.
- Ask only the clarifying questions you genuinely need to unblock the reporter.
- Reproduce the problem mentally and identify the most likely root cause.
- Suggest a concrete next step (code change, command to try, or environment tweak).
- Link to relevant files, lines, or documentation in the repository when helpful.
- Match the tone of a polite, professional maintainer.
- Do not invent facts about the codebase that are not reasonably supported.
- Do not promise fixes or timelines you cannot commit to.
<</requirements>>
<<output>>
Return a short response with:
1. "Acknowledge" — restate the issue in one sentence.
2. "Next steps" — what the reporter should try, or what you will investigate.
3. "Labels" — 1–3 existing GitHub label names that fit (e.g. "bug", "documentation", "needs-repro").

End with a thoughtful question that moves the conversation forward.
<</output>>
"""


@prompt(tags={"github", "commit", "message"}, version="1.0")
def github_commit_message_prompt(changes_summary: str) -> str:
    return f"""
<<system>>
You are writing a git commit message that follows the Conventional Commits format.
<</system>>
<<changes_summary>>
{changes_summary}
<</changes_summary>>
<<requirements>>
- Use the format: ``<type>(<scope>): <subject>``.
- Allowed types: ``feat``, ``fix``, ``docs``, ``style``, ``refactor``, ``perf``, ``test``, ``build``, ``ci``, ``chore``, ``revert``.
- Subject must be in imperative mood, lowercase, no period at the end, and 50 characters or fewer when possible.
- Body (optional) must explain the *why*, not the *what* — wrap at 72 characters per line.
- Footer (optional) must reference any breaking changes (``BREAKING CHANGE: ...``) or issue numbers (``Refs: #123``).
- Do not mention tooling (no "Generated by", no Co-Authored-By trailers unless requested).
- Do not invent changes that are not in the summary.
<</requirements>>
<<output>>
Return only the final commit message — subject line, optional blank line, optional body, optional footer. Nothing else.
<</output>>
"""


# ---------------------------------------------------------------------------
# File-level commit messages
# ---------------------------------------------------------------------------

@prompt(tags={"github", "commit", "message", "file"}, version="1.0")
def file_commit_message_prompt(file_path: str, action: str, content_summary: str) -> str:
    return f"""
<<system>>
You are writing a single-file git commit message in Conventional Commits format.
<</system>>
<<file_path>>
{file_path}
<</file_path>>
<<action>>
{action}
<</action>>
<<content_summary>>
{content_summary}
<</content_summary>>
<<requirements>>
- ``action`` is one of ``create``, ``update``, or ``delete``. The commit type should reflect it (e.g. ``feat`` for create, ``refactor`` or ``fix`` for update, ``chore`` for delete).
- The scope should be the most relevant module or directory from the file path (e.g. ``auth``, ``api``, ``docs``). Omit the scope if there is no obvious one.
- Subject must be imperative, end without a period, and stay under 50 characters when possible.
- Do not invent changes that are not in the summary.
<</requirements>>
<<output>>
Return only the single-line commit message. No body, no footer, no quotes.
<</output>>
"""


@prompt(tags={"github", "commit", "message", "multi"}, version="1.0")
def push_files_commit_message_prompt(branch: str, file_summaries: str) -> str:
    return f"""
<<system>>
You are writing a multi-file git commit message in Conventional Commits format for an atomic commit created via the Git Data API.
<</system>>
<<branch>>
{branch}
<</branch>>
<<file_summaries>>
{file_summaries}
<</file_summaries>>
<<requirements>>
- The subject must capture the unifying intent of the change, not just one file.
- Use a top-level type (``feat``, ``fix``, ``refactor``, ``docs``, ``test``, ``chore``, ``perf``, ``build``, ``ci``, ``style``, ``revert``) and, if helpful, a scope.
- Body (optional) lists the notable file-level changes as bullet points, wrapped at 72 characters.
- Reference related issues as ``Refs: #123`` if the branch or summaries hint at one.
- Do not mention the Git Data API, blobs, trees, or refs in the message.
<</requirements>>
<<output>>
Return the commit message: subject line, optional blank line, optional body, optional footer. Nothing else.
<</output>>
"""


# ---------------------------------------------------------------------------
# Branches
# ---------------------------------------------------------------------------

@prompt(tags={"github", "branch", "name"}, version="1.0")
def branch_name_prompt(intent: str, base_branch: str = "main") -> str:
    return f"""
<<system>>
You generate short, conventional git branch names from a developer intent.
<</system>>
<<intent>>
{intent}
<</intent>>
<<base_branch>>
{base_branch}
<</base_branch>>
<<requirements>>
- Use one of the conventional prefixes when applicable: ``feature/`` or ``feat/`` for new features, ``fix/`` or ``bugfix/`` for bug fixes, ``chore/`` for tooling or maintenance, ``docs/`` for documentation, ``refactor/`` for restructuring, ``test/`` for test changes, ``hotfix/`` for urgent production fixes.
- Use kebab-case after the prefix: lowercase letters, digits, and hyphens only.
- Keep the suffix meaningful but compact (3-6 words is ideal).
- Never include spaces, uppercase letters, or special characters other than ``/`` and ``-``.
- Do not include the base branch name in the new branch name.
<</requirements>>
<<output>>
Return only the branch name. Nothing else.
<</output>>
"""


# ---------------------------------------------------------------------------
# Issues
# ---------------------------------------------------------------------------

@prompt(tags={"github", "issue", "title"}, version="1.0")
def issue_title_prompt(description: str) -> str:
    return f"""
<<system>>
You write concise, well-scoped GitHub issue titles.
<</system>>
<<description>>
{description}
<</description>>
<<requirements>>
- Treat the input as the reporter's raw description. Extract the essence.
- Title must be under 80 characters and must not end with a period.
- Use sentence case (capitalize only the first word and proper nouns).
- Prefer a noun phrase ("Token refresh fails on Safari") over an imperative ("Fix token refresh").
- Do not prefix with tags like ``[BUG]`` or ``(Feature)`` — labels carry that information.
- Do not invent facts that are not in the description.
<</requirements>>
<<output>>
Return only the title. Nothing else.
<</output>>
"""


@prompt(tags={"github", "issue", "body"}, version="1.0")
def issue_body_prompt(title: str, context: str) -> str:
    return f"""
<<system>>
You write clear, well-structured GitHub issue bodies using Markdown.
<</system>>
<<title>>
{title}
<</title>>
<<context>>
{context}
<</context>>
<<requirements>>
- Use this template:
  - ``## Summary`` — one or two sentences describing the problem or request.
  - ``## Steps to reproduce`` (for bugs) or ``## Proposal`` (for features) — bullet points where useful.
  - ``## Expected behavior`` — what the reporter or user expected to happen.
  - ``## Actual behavior`` (for bugs only) — what currently happens.
  - ``## Environment`` — bullet list of relevant versions, OS, browser, etc., only if present in the context.
- Do not invent details, versions, or environment information that the context does not provide.
- Keep the body under 4000 characters.
<</requirements>>
<<output>>
Return only the Markdown body. Nothing else.
<</output>>
"""


@prompt(tags={"github", "issue", "comment"}, version="1.0")
def issue_comment_prompt(issue_context: str, intent: str) -> str:
    return f"""
<<system>>
You are a maintainer replying on a GitHub issue thread.
<</system>>
<<issue_context>>
{issue_context}
<</issue_context>>
<<intent>>
{intent}
<</intent>>
<<requirements>>
- Write a single Markdown comment body (no surrounding ``---`` fences).
- Be polite, concise, and concrete.
- If asking for information, list each question as a bullet point so the reporter can answer them in order.
- If providing a fix, include code fences with the correct language tag.
- Do not repeat the issue context back to the reporter.
<</requirements>>
<<output>>
Return only the comment body. Nothing else.
<</output>>
"""


# ---------------------------------------------------------------------------
# Pull requests
# ---------------------------------------------------------------------------

@prompt(tags={"github", "pull_request", "title"}, version="1.0")
def pr_title_prompt(branch_name: str, change_summary: str) -> str:
    return f"""
<<system>>
You write concise, well-scoped GitHub pull request titles.
<</system>>
<<branch_name>>
{branch_name}
<</branch_name>>
<<change_summary>>
{change_summary}
<</change_summary>>
<<requirements>>
- Title must be under 80 characters and must not end with a period.
- Use sentence case.
- Prefer a noun phrase describing the outcome ("Add CSV export to /reports") over an imperative ("Add CSV export").
- Avoid meta-prefixes like ``WIP:`` unless explicitly told the PR is still a draft.
- Do not invent changes that are not in the summary.
<</requirements>>
<<output>>
Return only the title. Nothing else.
<</output>>
"""


@prompt(tags={"github", "pull_request", "body"}, version="1.0")
def pr_body_prompt(diff: str, commits_summary: str = "") -> str:
    return f"""
<<system>>
You write clear, well-structured GitHub pull request descriptions using Markdown.
<</system>>
<<diff>>
{diff}
<</diff>>
<<commits_summary>>
{commits_summary}
<</commits_summary>>
<<requirements>>
- Use this template:
  - ``## Summary`` — 1–3 bullets describing what changed and why.
  - ``## Changes`` — bullets grouping the diff by file area or logical concern.
  - ``## Test plan`` — bullets describing how the change was or should be verified.
  - ``## Related`` — references like ``Fixes #123`` or ``Refs #456`` if mentioned in the inputs.
- Keep the body under 6000 characters.
- Be specific: cite file paths or symbols when relevant.
- Do not invent changes that are not in the diff or commits.
<</requirements>>
<<output>>
Return only the Markdown body. Nothing else.
<</output>>
"""


@prompt(tags={"github", "pull_request", "review", "body"}, version="1.0")
def pr_review_body_prompt(review_points: str) -> str:
    return f"""
<<system>>
You are writing the body of a GitHub pull request review (the comment that accompanies APPROVE / REQUEST_CHANGES / COMMENT).
<</system>>
<<review_points>>
{review_points}
<</review_points>>
<<requirements>>
- Group the points into the sections ``Blocking``, ``Suggestions``, ``Nits`` if not already grouped.
- Use Markdown bullet points inside each section.
- Be concise; one to three sentences per bullet.
- Reference file paths or line numbers if present in the input.
- Avoid repeating the original review points verbatim when grouping them.
<</requirements>>
<<output>>
Return only the Markdown review body. Nothing else.
<</output>>
"""


@prompt(tags={"github", "pull_request", "review", "comment"}, version="1.0")
def pr_review_comment_prompt(code_snippet: str, concern: str) -> str:
    return f"""
<<system>>
You are writing a single line-level review comment on a GitHub pull request.
<</system>>
<<code_snippet>>
{code_snippet}
<</code_snippet>>
<<concern>>
{concern}
<</concern>>
<<requirements>>
- Keep the comment under 600 characters.
- State the concern in one sentence, then suggest a concrete fix.
- Use code fences with the appropriate language when showing a code change.
- Be specific — do not generalize beyond what the snippet supports.
- Match the tone of a polite, professional code reviewer.
<</requirements>>
<<output>>
Return only the comment body. Nothing else.
<</output>>
"""


# ---------------------------------------------------------------------------
# Merge commits
# ---------------------------------------------------------------------------

@prompt(tags={"github", "pull_request", "merge", "title"}, version="1.0")
def merge_commit_title_prompt(pr_title: str, pr_number: int) -> str:
    return f"""
<<system>>
You are writing the title of a merge commit for a GitHub pull request.
<</system>>
<<pr_title>>
{pr_title}
<</pr_title>>
<<pr_number>>
{pr_number}
<</pr_number>>
<<requirements>>
- Default form: ``Merge pull request #{pr_number} from <branch>``. Use the provided title when branch name is not known.
- If ``pr_title`` is meaningful, prefer ``Merge pull request #{pr_number}: {pr_title}`` and trim the title to under 70 characters total.
- Never include Co-Authored-By or Generated-by trailers.
<</requirements>>
<<output>>
Return only the merge commit title. Nothing else.
<</output>>
"""


@prompt(tags={"github", "pull_request", "merge", "body"}, version="1.0")
def merge_commit_message_prompt(pr_title: str, pr_number: int, pr_body: str = "") -> str:
    return f"""
<<system>>
You are writing the body of a merge commit for a GitHub pull request.
<</system>>
<<pr_title>>
{pr_title}
<</pr_title>>
<<pr_number>>
{pr_number}
<</pr_number>>
<<pr_body>>
{pr_body}
<</pr_body>>
<<requirements>>
- Start with a single-line summary sentence of the merged PR.
- If ``pr_body`` is non-empty, include a short excerpt (1-3 bullets) summarizing the most important changes.
- Wrap lines at 72 characters.
- Do not add Co-Authored-By or Generated-by trailers.
- Reference the source PR via ``Refs: #{pr_number}`` only if not already implied.
<</requirements>>
<<output>>
Return the merge commit body (no title line). Plain text with bullets where useful. Nothing else.
<</output>>
"""


# ---------------------------------------------------------------------------
# Repositories
# ---------------------------------------------------------------------------

@prompt(tags={"github", "repository", "description"}, version="1.0")
def repo_description_prompt(repo_name: str, summary: str) -> str:
    return f"""
<<system>>
You write concise GitHub repository descriptions (the short tagline under the repo name on github.com).
<</system>>
<<repo_name>>
{repo_name}
<</repo_name>>
<<summary>>
{summary}
<</summary>>
<<requirements>>
- Hard limit: 350 characters.
- Lead with what the repository *does*, not what it *is*.
- Use sentence case, no trailing period.
- Mention the language or stack only if it is the primary distinguishing feature.
- Do not include marketing fluff or emojis.
<</requirements>>
<<output>>
Return only the description. Nothing else.
<</output>>
"""